language: python
python: 2.7
env:
    - LOGSTASH_VERSION=5.1.1
addons:
  apt:
    packages: openjdk-8-jre-headless
install:
    - cd $HOME
    - easy_install vsc-base
    - wget -q https://artifacts.elastic.co/downloads/logstash/logstash-${LOGSTASH_VERSION}.tar.gz
    - tar -xzf logstash-${LOGSTASH_VERSION}.tar.gz
    - export PATH=$HOME/logstash-${LOGSTASH_VERSION}/bin:$PATH
script:
    - cd $TRAVIS_BUILD_DIR/tests && python runtest.py
